name: CI

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: e2e Tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run e2e-dashboard
